### PR TITLE
Commenting out the replace for git@ addresses to allow for key based …

### PR DESCRIPTION
**Pull request by PhearZero**
…management

### CODE REVIEW

**Comment by jpillora** [comment]
This breaks existing uses of the `@` notation though

**Comment by jpillora** [comment]
Ah yeah, git URLs can contain an `@` at the beginning for authentication, I totally forgot about that. I think the correct fix is to make a regexp better. Authentication always comes before the domain. The commit reference always comes after.

**Comment by PhearZero** [comment]
Sounds good and I love the project!! I just did a hotfix to get it to work in my env. Didn't understand the reasoning behind the replace. From what I gleaned it seemed like the git client should handle the authentication but I haven't tested. Either way thanks again for the great tool!

**Comment by PhearZero** [comment]
I went ahead and threw in nodejs url.parse to strip the authentication from the valid http(s) urls. What do you think about adding authentication to the config as a feature/enhancment? I realized stripping the authentication is a good thing when in a shared env!! Either way cheers!

**Comment by jpillora** [comment]
Hi Michael, looks like a good way to grab authentication though we still
need to set repoRef (see previous code)

**Comment by PhearZero** [comment]
Thanks Jaime, still a newb trying to get my js chops down. Hopefully c71a2eb takes care of repoRef. Keep up the good work!

**Comment by jpillora** [comment]
thanks for the PR, ill publish it to npm tonight

**Comment by PhearZero** [comment]
No prob, thanks for the update. I'm gonna update some repos and ping some users. Everybody digs the project. Hoping to release some of the devops work to the public from the contract work at a few diff companies, grunt-source is at the heart of it all. Cheers!

**Comment by jpillora** [comment]
Ah awesome, glad it's getting some good use by people :)

**Pull request merged**
